- name: Find out playbook's path
  shell: pwd
  register: playbook_path_output

- name: change index file
  copy:
    src: helloworld1.html
    dest: /var/www/html/index.html
  become: yes
  notify: restart service apache  