- name: install apache2 with generic package manager
  package:
    name: apache2
    state: present
  become: true
  notify: restart service apache

- name: add hosts name
  lineinfile: 
    path: /etc/hosts
    line: "{{ item }} host{{index}}"
  become: true
  loop: "{{ groups['all'] }}"
  loop_control:
    index_var: index

- name: print all group and hosts
  shell: "wall {{ item }}"
  loop: "{{ groups['all'] }}"
